name: branch-cleanup
on:
  pull_request:
    branches:
      - master
jobs:
  cleanup-branch:
    name: auto delete branch on merge
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/actions/github/branch-cleanup@0.3.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        NO_BRANCH_DELETED_EXIT_CODE: 0
